name: Create Release

on:
  push:
    branches:
      - master
  workflow_dispatch:
  watch:
    paths:
      - CHANGELOG.md

permissions:
  contents: write

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install shellcheck
        run: sudo apt-get install -y shellcheck

      - name: Install shfmt
        run: |
          sudo apt-get install -y software-properties-common
          sudo add-apt-repository ppa:longsleep/golang-backports -y
          sudo apt-get update
          sudo apt-get install -y golang-go
          go install mvdan.cc/sh/v3/cmd/shfmt@latest
          export PATH=$PATH:$(go env GOPATH)/bin

      - name: Run shellcheck
        run: |
          shellcheck ./path/to/your/scripts/*.sh

      - name: Run shfmt
        run: |
          shfmt -w ./path/to/your/scripts/*.sh


  test:
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  create_release:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Extract version from CHANGELOG.md
        id: extract_version
        run: |
          version=$(grep -oP '## \[\K[^\]]+' CHANGELOG.md | head -1)
          echo "version=$version" >> $GITHUB_ENV

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          tag_name: ${{ env.version }}
          release_name: Release ${{ env.version }}
          body: |
            See the changelog for more details:
            https://github.com/${{ github.repository }}/blob/master/CHANGELOG.md
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_content_type: application/octet-stream
