name: Create Release

on:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  create_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get the latest tag
        id: get_tag
        run: echo ::set-output name=tag::$(git describe --tags --abbrev=0)

      - name: Check if tag already exists
        id: check_tag
        run: |
          git fetch --tags
          if git rev-parse "$GITHUB_REF" >/dev/null 2>&1; then
            echo "Tag $GITHUB_REF already exists. Exiting."
            exit 0
          fi

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Create Release Notes
        id: create_release_notes
        run: |
          CHANGELOG=$(awk '/## \['"${{ steps.get_tag.outputs.tag }}"'\]/{flag=1;next}/## \[/{flag=0}flag' CHANGELOG.md)
          echo "::set-output name=notes::$CHANGELOG"

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_tag.outputs.tag }}
          release_name: Release ${{ steps.get_tag.outputs.tag }}
          body: ${{ steps.create_release_notes.outputs.notes }}
          draft: false
          prerelease: false
